netobserv/network-observability-cli

Makefile, README.md, res/functions.sh
Add shellcheck bash scripts linter and fix linter error
Add make help target
=> NETOBSERV-1498 Add shellcheck linter for bash and make help target

oc/oc-netobserv-flows, oc/oc-netobserv-packets, res/functions.sh
Since `functions.sh` is called from oc commands, we need to adapt the scripts to ensure variables are bound.
Else the scripts simply crash when filters are not set:
```
$ oc netobserv packets
/usr/local/bin/oc-netobserv-packets: line 5: $1: unbound variable
```
Also removed trace since it makes difficult to read the custom messages that are supposed to guide you.
=> Remove bash trace and manage unbound var

.github/dependabot.yml, .github/pull_request_template.md, .github/release.yml, .github/workflows/greetings.yml, .github/workflows/pull_request.yml, .github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .github/workflows/rm-ok-to-test.yaml, .gitignore, .golangci.yml, LICENSE, Makefile, OWNERS, cmd/flow-capture.go, cmd/packet-capture.go, oc/oc-netobserv-flows, oc/oc-netobserv-packets, scripts/inject.sh
Adding github files + miscs and allow injecting image from Make target
Also see prow configs: https://github.com/openshift/release/pull/50198
Based on https://github.com/netobserv/network-observability-cli/pull/3, merge it first and rebase when dependencies are updated
=> NETOBSERV-1499 Github config for CLI

Makefile, README.md
install golangci-lint only if its not installed 
n/a
=> install golangci-lint only if its not installed and update readme

.github/workflows/pull_request.yml, .github/workflows/push_image.yml, cmd/flow_capture.go, cmd/flow_capture_test.go, cmd/map_format.go, cmd/map_format_test.go, cmd/packet_capture.go, cmd/packet_capture_test.go, cmd/root.go, cmd/root_test.go, go.mod
Add testing to table displays
- Flows
- Packets
n/a
=> NETOBSERV-1498 add testing to table displays

Makefile, commands/netobserv, res/flow-capture.yml, scripts/functions.sh
how we can pass in flow filter configs and use it to update flow collector manifests
Example
```sh
netobserv flows --interfaces=eth0 --enable=true --protocol="TCP" --cidr=0.0.0.0/0 --port-range="80-100" --peer-ip="1.1.1.1" --action=Accept
```
n/a
=> NETOBSERV-1609: parse flow filter configs and use it to update manifest

commands/netobserv, scripts/functions.sh
move filters help to the main help menu
```shell
./commands/netobserv help
Netobserv allows you to capture flow and packets from your cluster.
Find more information at: https://github.com/netobserv/network-observability-cli/
Syntax: netobserv [flows|packets|cleanup] [filters]
options:
flows      Capture flows information. You can specify an optionnal interface name as filter such as 'netobserv flows br-ex'.
Options:
--interfaces: interfaces to monitor
--enable_pktdrop: enable packet drop (default: true)
--enable_dns: enable DNS tracking (default: true)
--enable_rtt: enable RTT tracking (default: true)
--enable_filter: enable flow filter (default: false)
--direction: flow filter direction
--cidr: flow filter CIDR (default: 0.0.0.0/0)
--protocol: flow filter protocol (default: TCP)
--sport: …
```
=> move the help menu for filters to the main help menu

scripts/inject.sh
Attempt to make `sed` working on MacOs.
Run the following target to give a try:
```bash
$ make oc-commands 
DIST_DIR=build \
K8S_CLI_BIN=oc \
IMAGE=quay.io/julien/network-observability-cli:main \
PULL_POLICY=Always \
VERSION=main \
./scripts/inject.sh
updating CLI images to quay.io/julien/network-observability-cli:main
updating CLI pull policy to Always
updating CLI version to main
updating K8S CLI to oc
prefixing with oc-
pull policy not provided, keeping current ones
output generated in build folder
```
The generated file `./build/oc-netobserv` should contains YAMLs and your quay image with version main.
n/a
* QE requirements (check …
=> NETOBSERV-1623 update sed commands to support macos

commands/netobserv
```
NETOBSERV_COLLECTOR_IMAGE=xxx oc netobserv flows
```
n/a
=> Allow custom image at run time

commands/netobserv
=> [backport] allow custom image at run time (#42)

Makefile, commands/netobserv, res/flow-capture.yml, res/packet-capture.yml, scripts/functions.sh, scripts/inject.sh
- Configure agent image at build time using `AGENT_IMAGE` param
```
$ USER=netobserv VERSION=main AGENT_IMAGE=quay.io/netobserv/netobserv-ebpf-agent:release-1.6 make oc-commands 
DIST_DIR=build \
K8S_CLI_BIN=oc \
IMAGE=quay.io/netobserv/network-observability-cli:main \
PULL_POLICY=Always \
AGENT_IMAGE=quay.io/netobserv/netobserv-ebpf-agent:release-1.6 \
VERSION=main \
./scripts/inject.sh
updating CLI images to quay.io/netobserv/network-observability-cli:main
updating CLI version to main
updating CLI pull policy to Always
updating eBPF agent images to quay.io/netobserv/netobserv-ebpf-agent:release-1.6
updating K8S CLI to oc
prefixing with oc-
pull policy not provided, keeping current ones
output generated in build folder
```
- Override agent image at run time using `NETOBSERV_AGENT_IMAGE` …
=> NETOBSERV-1678: allow agent image configuration

commands/netobserv, docs/netobserv_cli_packets_config.md, e2e/capture_test.go, e2e/script_test.go, res/flow-capture.yml, res/packet-capture.yml, scripts/functions.sh
add filter capability for pca feature
Example from running on `Kind` cluster
- build commands locally and use agent custom image
```sh
NETOBSERV_AGENT_IMAGE=quay.io/netobserv/netobserv-ebpf-agent:f525832 ./build/oc-netobserv packets --protocol="TCP" --port=443
```
output pcap
```sh
tcpdump -r 2024-06-27T110645Z.pcap 
reading from file 2024-06-27T110645Z.pcap, link-type EN10MB (Ethernet), snapshot length 262144
07:06:57.502363 IP 172.18.0.3.41396 > ec2-52-204-93-25.compute-1.amazonaws.com.https: Flags [P.], seq 2078794407:2078794438, ack 1312010586, win 458, options [nop,nop,TS val 3614985982 ecr 3018431589], length 31
07:06:57.502422 IP 172.18.0.3.41396 > ec2-52-204-93-25.compute-1.amazonaws.com.https: Flags [F.], seq 31, ack 1, win 458, options [nop,nop,TS val 3614985982 ecr 3018431589], …
```
=> NETOBSERV-1617: use filter with packets capture feature

scripts/functions.sh
fix a bug introduced when shared args processing between packets and flows in #54 
after `shift` command the position of arguments will change
n/a
=> NETOBSERV-1749: fix flows and packets arg processing

commands/netobserv, e2e/common.go, scripts/functions.sh
Ask for copy on exit
```
INFO[0034] Ctrl-C pressed, exiting program.             
kubernetes-admin
Copy the capture output locally ?y
Copying collector output files...
Cleaning up... namespace "netobserv-cli" deleted
```
```
INFO[0004] Ctrl-C pressed, exiting program.             
kubernetes-admin
Copy the capture output locally ?n
copy skipped
Cleaning up... namespace "netobserv-cli" deleted
```
The total capture size will be displayed in https://github.com/netobserv/network-observability-cli/pull/59
n/a
=> NETOBSERV-1693 Prompt for copying files on exit

cmd/flow_capture.go, cmd/packet_capture.go, cmd/root.go, commands/netobserv, docs/netobserv_cli_flows_config.md, docs/netobserv_cli_packets_config.md, e2e/script_test.go, res/flow-capture.yml, res/packet-capture.yml, scripts/functions.sh
Auto teardown after some time / number of flows / packets
Also took the opportunity to add log level argument and improve display
```
oc netobserv flows --max-time=30s --max-bytes=1000000 --log-level=trace --sport=443 --direction=Ingress
```
```
Running network-observability-cli as Flow Capture
Log level: trace Duration: 28s Capture size: 116KB
Filters:    sport=443 direction=Ingress
```
```
--log-level: components logs (default: info)
--max-time: maximum capture time (default: 5m)
--max-bytes: maximum capture bytes (default: 50000000 = 50MB)
```
n/a
=> NETOBSERV-1684 Auto teardown after some time / number of flows / packets

commands/netobserv, docs/netobserv_cli_flows_config.md, docs/netobserv_cli_packets_config.md, scripts/functions.sh
@Amoghrd would that work for you ?
```
--copy=true|false|prompt
```
by default the `prompt` is asked at the end of the collection. If the user specify `--copy=true` or `--copy=false`, the corresponding action is done without prompt.
n/a
=> NETOBSERV-1693 Prompt for copying files on exit followup

Dockerfile
Add `oc-commands` output to collector image to easy get it from CI.
This could also be usefull for users having the container image but not the script installed locally :) 
n/a
=> NETOBSERV-1627 Add commands to image for CI

res/flow-capture.yml, res/packet-capture.yml, scripts/functions.sh
Allow filtering TCP/UDP/SCTP using two ports syntax like "90,100" to filter either on port 90 or 100
https://github.com/netobserv/netobserv-ebpf-agent/pull/389
=> NETOBSERV-1803: Allow flow filtering for L4 protocols using two ports

commands/netobserv, docs/netobserv_cli.adoc, scripts/functions.sh, scripts/generate-doc.sh
Polishing generated doc from https://github.com/openshift/openshift-docs/pull/81064 feedback
n/a
=> OSDOCS-11821 help & doc cleanup

cmd/packet_capture.go, cmd/root.go
Fix CLI packet enrichment issue where all packets were pointing the same info
n/a
=> NETOBSERV-1850 fix cli enrichment issue

.tekton/network-observability-cli-container-pull-request.yaml, .tekton/network-observability-cli-container-push.yaml, Dockerfile, Makefile
Address error in buildah build and also enable hermetic build which is a downstream requirement.
n/a
=> NETOBSERV-1633: Fix multiarch build with new buildah version

.github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, Dockerfile, Makefile, cli.Dockerfile, main.go
- Reducing the Dockerfile dependencies allows faster dev builds
- Optimize docker caching wrt oc-commands dependencies
- Align also with other repos wrt build date / version (it was not correctly implemented, with variable names mismatch)
- Remove duplicated "make build" definitions
=> Align build steps - distinguish clean vs dev builds

res/flow-capture.yml, res/packet-capture.yml, scripts/functions.sh
Add option to set a single node selector to eBPF agents.
```
$ ./build/oc-netobserv flows --node-selector=kubernetes.io/hostname:netobserv-cli-cluster-worker
```
n/a
=> NETOBSERV-1906 add nodeSelector

.mk/dev.mk, Makefile, cmd/flow_capture.go, cmd/mocks.go, cmd/packet_capture.go, cmd/root.go, go.mod
Add very simple mocks to the CLI to avoid running the whole stack for UI changes.
n/a
=> add mocks to cli

res/flow-capture.yml, res/packet-capture.yml, scripts/functions.sh
Implement FLP regexes filters in CLI. Example:
```
NETOBSERV_AGENT_IMAGE=quay.io/jpinsonn/netobserv-ebpf-agent:1692 ./build/oc-netobserv flows --regexes=SrcK8S_Namespace~netobserv-cli
```
https://github.com/netobserv/flowlogs-pipeline/pull/740
=> will need to update eBPF agent since CLI rely on direct+flp mode
=> NETOBSERV-1909 filter regexes

Dockerfile, cmd/flow_capture.go, cmd/packet_capture.go, cmd/root.go, cmd/root_test.go, commands/netobserv, e2e/script_test.go, res/service-account.yml, scripts/functions.sh
Add new options / commands to run in background:
- `--background=true` to run either flow or packet capture without the need to connect the collector pod
- `follow` command to connect an existing collector and see its output
- `stop` to remove agents without removing the collector pod
- `copy` to copy the output of a running / ended collection
When the collection limits are reached (max time or bytes), the collector pod destroy the agents using netobserv CLI itself: `oc netobserv stop`.
The collector pod keep running to let the user copy the output before cleaning the capture.
The cleanup mechanism has been improved by cleaning both daemonset and pod before cleaning up the namespace.
Run a short flow capture:
```
$ ./build/oc-netobserv flows --background=true --max-time=30s
```
Connect …
=> NETOBSERV-1907 run in background

Dockerfile, commands/netobserv, res/collector-service.yml, res/flow-capture.yml, res/namespace.yml, res/packet-capture.yml, res/service-account.yml, scripts/functions.sh
Allow custom namespace using `NETOBSERV_NAMESPACE` env variable.
Example:
```
$ NETOBSERV_NAMESPACE=test ./build/oc-netobserv flows
```
Based on https://github.com/netobserv/network-observability-cli/pull/102
=> NETOBSERV-1908 Be able to customize namespace

scripts/functions.sh
Get subnets from flows:
```
oc netobserv flows --get-subnets
```
Will need https://github.com/netobserv/network-observability-cli/pull/105 to add the columns in a followup
Based on https://github.com/netobserv/network-observability-cli/pull/121
=> NETOBSERV-1578 subnets labels

res/flow-capture.yml, res/packet-capture.yml, scripts/functions.sh
ebpf agent will support multi flow filter rules however we will limit cli to only single rule
till we find a more efficient way to pass in more rules
https://github.com/netobserv/netobserv-ebpf-agent/pull/473
=> NETOBSERV-2005: Allow populaiting only single filter rules for cli usecase

Dockerfile.downstream, Makefile
- Add missing oc script to downstream dockerfile
- Skip dependencies check to force versions
n/a
=> Misc-fixes

res/flow-capture.yml
since cli run as `privileged` we need to include netns volume mount to avoid warning when the agent starts
n/a
=> add netns volume mount to avoid agent warning when it starts

.github/workflows/pull_request.yml, .github/workflows/pull_request_e2e.yml, .github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .golangci.yml, Dockerfile, Dockerfile.downstream, Makefile, cmd/flow_capture.go, cmd/flow_capture_test.go, cmd/flow_db.go, cmd/packet_capture.go, cmd/root.go, e2e/cluster/kind.go
Upgrading linter showed some potential actual bugs during cleanup / exit, where deferred functions aren't called when something like log.Fatal or os.Exit is called, so I had to move things around to fix that (basically: having functions returning errors in case of doing something Fatal, and dealing with fatality in caller)
=> move to go 1.23

scripts/functions.sh
It's conventional and more user-friendly to tell which answers are accepted (even if more than that would actually work), so user isn't worried about typing wrong things
Also, no space before question mark in English
=> Nit: better text asking for copying

cmd/flow_capture.go, cmd/flow_capture_test.go, cmd/map_format.go, cmd/options.go
Refactor display options to improve code quality. Also took the chance to add namespace enrichment view
n/a
=> NETOBSERV-2016 refactor display options

.github/workflows/pull_request.yml
Following https://github.com/netobserv/network-observability-cli/pull/144#issuecomment-2602387025
=> skip ci faillure on coverage upload issues

scripts/functions.sh
Check node selector before running the capture.
- warn and exit if no match
- display matches if found
n/a
=> NETOBSERV-2020 check node selector

Makefile, commands/netobserv, scripts/dependencies_check.sh, scripts/generate-doc.sh, scripts/inject.sh, scripts/krew.sh, scripts/update-config.sh
- use `#!/usr/bin/env bash` on scripts
- require bash >= 4.2.0
n/a
=> NETOBSERV-1578 Fix bash issues on macos

res/flow-capture.yml, res/packet-capture.yml
Tolerations were missing to deploy on master nodes.
n/a
=> NETOBSERV-2030: deploy on master nodes

res/flow-capture.yml, res/packet-capture.yml, scripts/functions.sh
Extend flow filtering to include peerCIDR as an option
https://github.com/netobserv/netobserv-ebpf-agent/pull/501
=> NETOBSERV-2047: Add peerCIDR flow filtering support

Dockerfile, Dockerfile.downstream
Backport of https://github.com/netobserv/network-observability-cli/pull/169
=> NETOBSERV-2112: Make build FIPS compliant [1.8 backport]

res/metrics-pipeline-config.json
Backport of https://github.com/netobserv/network-observability-cli/pull/174
=> [Backport] NETOBSERV-2107 Disable worload metrics

res/metrics-pipeline-config.json
Disable DNS and RTT workload metrics to avoid cardinality issues.
n/a
=> NETOBSERV-2107 disable dns & rtt workload metrics

scripts/functions.sh, scripts/help.sh
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
(cherry picked from commit a2dd55daa15f5f98cd3acb6b21db99b17c35d27a)
n/a
=> NETOBSERV-2123: remove 1.8 unsupported features from cli[BP to 1.8]

Dockerfile.downstream
Bump ose cli image to 4.18
https://catalog.redhat.com/software/containers/openshift4/ose-cli-rhel9/6528096620ebdcf82af4cbf9?architecture=amd64&image=67a16a5ebcf48c6835f943f7&container-tabs=overview
=> bump ose cli image

Dockerfile.downstream
Backport of https://github.com/netobserv/network-observability-cli/pull/191
=> [Backport] bump ose cli image

Makefile
I'm experiencing memory leaks using the old version of golangci-lint
Updating it fixes the issue
=> update linter to avoid memory leak

scripts/dependencies_check.sh
If `yq` isnt installed, then status code returned will be 1. Krew installs plugin with `set -e` option, which means the script will silently exit at this point without further instructions on whats wrong.
In this PR we add `|| true` to get status code 0 and continue script.
n/a
=> gracefully fail on which check

cmd/flow_capture.go, scripts/functions.sh
[NETOBSERV-2133](https://issues.redhat.com/browse/NETOBSERV-2133) CLI flows JSON 
n/a
=> NETOBSERV-2133 CLI flows JSON

README.md
- Put krew first (most people surely don't want to clone the repo in order to use the CLI)
- For each "run" example, add a version with krew
=> README: getting started section with Krew

scripts/functions.sh, scripts/help.sh
Allow multiple regexes filters to manage cases such as Src OR Dst
Example:
```
oc netobserv flows --regexes="SrcK8S_Namespace~net1" or --regexes="DstK8S_Namespace~net1"
```
n/a
=> NETOBSERV-2131 allow multiple regexes

cmd/config.yaml, commands/netobserv, e2e/yaml_test.go, res/service-account.yml, res/service-monitor.yml, scripts/functions.sh, scripts/help.sh
Add --yaml option to be able to test metrics command.
Also test flow & packet yaml output with filters
Based on https://github.com/netobserv/network-observability-cli/pull/146, merge it first !
=> NETOBSERV-2006 Cover all new features in e2e tests

commands/netobserv, docs/netobserv_cli.adoc, e2e/integration-tests/integration_test.go, e2e/script_test.go, scripts/functions.sh, scripts/help.sh
See https://github.com/netobserv/flowlogs-pipeline/pull/930
Run with FLP queries (e.g.) :
```bash
make flows COMMAND_ARGS="--query='DstK8S_Namespace=~\"openshift.*\"'"
oc netobserv flows --query='DstK8S_Namespace=~"openshift.*"'
```
For more info on the query language: https://github.com/netobserv/flowlogs-pipeline/blob/main/docs/filtering.md
n/a
=> NETOBSERV-2187: adapt regex to new query language in flp

docs/netobserv_cli.adoc, scripts/functions.sh, scripts/generate-doc.sh, scripts/help.sh
Add sampling and exclude_interfaces options
n/a
=> NETOBSERV-2118 add missing sampling and exclude interfaces options

res/flow-capture.yml
Backport of https://github.com/netobserv/network-observability-cli/pull/308
=> Backport NETOBSERV-2257: identify interfaces by index and mac

cmd/metric_capture.go, cmd/root.go, commands/netobserv, docs/netobserv_cli.adoc, scripts/functions.sh, scripts/generate-doc.sh, scripts/help.sh
- deploy collector when running metrics to force a maximum time
For now, the collector is only used as cleanup pod that removes the agents when the limit is reached.
In the future, that pod could handle more limits and even consume the generated metrics and expose these in the display using tview https://github.com/netobserv/network-observability-cli/pull/215
n/a
=> NETOBSERV-2253 CLI: enhance metrics safety option

cmd/flow_display.go, go.mod
Linter error was:
```
cmd/flow_display.go:199:13: printf: non-constant format string in call to github.com/netobserv/network-observability-cli/cmd.writeBuf (govet)
```
Using the conventional pattern of "func" vs "funcf" to distinguish function signatures with or without formatting/varg injection
=> fix linter issue with go1.24: distiguish writeBuf and writeBuff

scripts/functions.sh
The eBPF agent errors at startup will be displayed in CLI.
Example on OCP 4.15 with latest eBPF agent on packet capture (unsupported kernel):
```
Checking dependencies... 
'yq' is up to date (version v4.45.1).
'bash' is up to date (version v5.2.37).
Setting up... 
kube:admin
creating netobserv-cli namespace
namespace/netobserv-cli created
creating service account
serviceaccount/netobserv-cli created
clusterrole.rbac.authorization.k8s.io/netobserv-cli unchanged
clusterrolebinding.rbac.authorization.k8s.io/netobserv-cli unchanged
creating collector service
service/collector created
creating packet-capture agents
opt: filter_protocol, value: TCP
daemonset.apps/netobserv-cli created
Waiting for daemonset pods to be ready...
0/3 Ready. Reason(s): CrashLoopBackOff
ERROR: Daemonset pods failed …
```
=> NETOBSERV-2358 exit on daemonset failure with logs

Dockerfile.downstream
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> chore(KONFLUX-6210): fix and set name and cpe label for network-observability-cli-zstream
