netobserv/network-observability-cli

- Makefile
- res/functions.sh
fix bash `$2: unbound variable`
> fix $2: unbound variable runtime error

- Dockerfile
remove sqlite from DockerFile
n/a
> remove sqlite tool from container and inspect the db after it get copied

- Dockerfile
> fix output dir creation

- Dockerfile
> fix chown issue in main

- .github/workflows/pull_request.yml
- .github/workflows/push_image.yml
Attempt to fix dependabot failures
https://github.com/netobserv/network-observability-cli/actions/runs/8659316614/job/23869357082?pr=23
> add codecov token and fail on error

- docs/netobserv_cli_flows_config.md
- res/flow-capture.yml
- scripts/functions.sh
doc options for netobserv CLI
n/a
> NETOBSERV-1612: Netobserv cli configuration doc

- README.md
update readme and remove work in progress section
n/a
> update readme since all WIP tasks are completed

- Makefile
- commands/netobserv
- res/flow-capture.yml
- res/packet-capture.yml
- scripts/functions.sh
- scripts/inject.sh
https://github.com/netobserv/network-observability-cli/pull/48
> Backport of NETOBSERV-1678

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_e2e.yml
- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- .golangci.yml
- Dockerfile
> NETOBSERV-1707: move to go 1.22

- .tekton/network-observability-cli-container-pull-request.yaml
- .tekton/network-observability-cli-container-push.yaml
> Removed base image ref in konflux

- cli.Dockerfile
Add container file for cli used by Konflux
n/a
> NETOBSERV-1792 Add container file for cli used by Konflux

- scripts/functions.sh
Fix case where plugin complains about missing NETOBSERV_AGENT_IMAGE environment variable.
n/a
> NETOBSERV-1915 allow unbounded variables in functions

- scripts/functions.sh
Backport of https://github.com/netobserv/network-observability-cli/pull/94
> [BP] NETOBSERV-1915 allow unbounded variables in functions

- res/flow-capture.yml
- res/packet-capture.yml
https://github.com/netobserv/flowlogs-pipeline/pull/711 introduced breaking changes on kubernetes enrichment.
n/a
> Fix flp config

- res/flow-capture.yml
- res/packet-capture.yml
- scripts/functions.sh
add packet drop filter capabilities
https://github.com/netobserv/netobserv-ebpf-agent/pull/419
> NETOBSERV-1910 Add packet drops filtering to cli filter options

- .tekton/pipeline-ref.yaml
Fixing source build image tagging in konflux
n/a
> Fixing source build image tagging in konflux

- .tekton/pipeline-ref.yaml
Adding rpm scan task to konflux
n/a
> Adding rpm scan task to konflux

- .tekton/pipeline-ref.yaml
> Removing deprecated konflux results

- Dockerfile.downstream
Adding args to configure downstream images
n/a
> Adding args to configure downstream images

- Dockerfile.downstream
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
(cherry picked from commit cebd8d3916e77fa6d9c60f93348b0c2d06579ef7)
n/a
> Add missing description label to downstream containerfile [BP]

- Dockerfile.downstream
Fix downstream docker args and version
> fix args and version

- Dockerfile.downstream
Bump downstream dockerfile to 1.9.0
> bump-1.9.0

- docs/netobserv_cli.adoc
- scripts/generate-doc.sh
> remove useless enable filter option in doc

- .ci-operator.yaml
> update to golang 1.24 in CI

- Dockerfile.downstream
> Updating dependencies to fix vulnerabilities

- res/flow-capture.yml
- res/metric-capture.yml
- res/packet-capture.yml
> NETOBSERV-2366: use legacy attach mode

- cmd/config.yaml
- docs/netobserv_cli.adoc
- scripts/help.sh
> NETOBSERV-2355: Rename sampling ratio/rate -> interval
